apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: three-tier
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 029548526240.dkr.ecr.eu-west-3.amazonaws.com/backend-repository:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
